apiVersion: v2
name: bankingkata-api
description: A Helm chart for BankingKata API
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - banking
  - api
  - hexagonale
maintainers:
  - name: DevTeam
    email: dev@example.com
